return {
  {
    category = "Basic Motions",
    title = "Move Right",
    description = "Move the cursor to the marked position (column 4)",
    teach = { "l" },
    hint = "Press 'l' to move one character to the right",
    par = 4,
    solution = "llll",
    buffer_lines = {
      "....X......",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 1, 4 } },
  },
  {
    category = "Basic Motions",
    title = "Move Left",
    description = "Move the cursor back to the 'X' marker",
    teach = { "h" },
    hint = "Press 'h' to move one character to the left",
    par = 3,
    solution = "hhh",
    buffer_lines = {
      "..X........",
    },
    cursor_start = { 1, 5 },
    goal = { cursor = { 1, 2 } },
  },
  {
    category = "Basic Motions",
    title = "Move Down",
    description = "Move the cursor down to the last line",
    teach = { "j" },
    hint = "Press 'j' to move one line down",
    par = 4,
    solution = "jjjj",
    buffer_lines = {
      "Start here",
      "...........",
      "...........",
      "...........",
      "Goal line!",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 5, 0 } },
  },
  {
    category = "Basic Motions",
    title = "Move Up",
    description = "Move the cursor up to the first line",
    teach = { "k" },
    hint = "Press 'k' to move one line up",
    par = 3,
    solution = "kkk",
    buffer_lines = {
      "Goal line!",
      "...........",
      "...........",
      "Start here",
    },
    cursor_start = { 4, 0 },
    goal = { cursor = { 1, 0 } },
  },
  {
    category = "Basic Motions",
    title = "Navigate the Grid",
    description = "Navigate to the X at the bottom-right corner",
    teach = { "h", "j", "k", "l" },
    hint = "Combine h/j/k/l: h=left, j=down, k=up, l=right",
    par = 7,
    solution = "3j8l",
    buffer_lines = {
      "S . . . .",
      ". . . . .",
      ". . . . .",
      ". . . . X",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 4, 8 } },
  },
}
