return {
  {
    category = "Vertical Navigation",
    title = "Jump to Top",
    description = "Jump to the very first line of this config",
    teach = { "gg" },
    hint = "gg jumps to the first line of the buffer",
    par = 2,
    buffer_lines = {
      "[package]",
      'name = "my-project"',
      'version = "0.1.0"',
      "",
      "[dependencies]",
      'serde = "1.0"',
      'tokio = "1.0"',
      "",
      "[dev-dependencies]",
      'pretty_assertions = "1.3"',
    },
    cursor_start = { 8, 0 },
    goal = { cursor = { 1, 0 } },
  },
  {
    category = "Vertical Navigation",
    title = "Jump to Bottom",
    description = "Jump to the last line of this file",
    teach = { "G" },
    hint = "G (capital) jumps to the last line of the buffer",
    par = 1,
    buffer_lines = {
      "import os",
      "import sys",
      "",
      "def main():",
      '    print("Hello!")',
      "    return 0",
      "",
      'if __name__ == "__main__":',
      "    sys.exit(main())",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 9, 0 } },
  },
  {
    category = "Vertical Navigation",
    title = "Jump to Line",
    description = "Jump directly to line 8 where the function starts",
    teach = { "{n}G" },
    hint = "{n}G jumps to line number n. For example 8G goes to line 8",
    par = 3,
    buffer_lines = {
      "package main",
      "",
      "import (",
      '    "fmt"',
      '    "net/http"',
      ")",
      "",
      "func handler(w http.ResponseWriter, r *http.Request) {",
      '    fmt.Fprintf(w, "Hello!")',
      "}",
      "",
      "func main() {",
      '    http.HandleFunc("/", handler)',
      '    http.ListenAndServe(":8080", nil)',
      "}",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 8, 0 } },
  },
  {
    category = "Vertical Navigation",
    title = "Precise Line Jump",
    description = "Jump to line 12 where main() is defined",
    teach = { "{n}G" },
    hint = "Type 12G to jump directly to line 12",
    par = 4,
    buffer_lines = {
      "package main",
      "",
      "import (",
      '    "fmt"',
      '    "net/http"',
      ")",
      "",
      "func handler(w http.ResponseWriter, r *http.Request) {",
      '    fmt.Fprintf(w, "Hello!")',
      "}",
      "",
      "func main() {",
      '    http.HandleFunc("/", handler)',
      '    http.ListenAndServe(":8080", nil)',
      "}",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 12, 0 } },
  },
  {
    category = "Vertical Navigation",
    title = "Scroll Up",
    description = "From the bottom, jump back up to line 3 (the import)",
    teach = { "{n}G", "gg" },
    hint = "Use 3G to jump to line 3, or gg then jj",
    par = 3,
    buffer_lines = {
      "#!/usr/bin/env node",
      "",
      'const express = require("express");',
      'const cors = require("cors");',
      'const helmet = require("helmet");',
      "",
      "const app = express();",
      "app.use(cors());",
      "app.use(helmet());",
      "",
      'app.listen(3000, () => console.log("Running"));',
    },
    cursor_start = { 11, 0 },
    goal = { cursor = { 3 } },
  },
}
