return {
  {
    category = "Dot Repeat",
    title = "Repeat Change",
    description = "Change 'var' to 'const' on all three lines using cw and .",
    teach = { "." },
    hint = "cw changes a word. After Esc, use j0. to move down and repeat the change",
    par = 14,
    buffer_lines = {
      "var name = 'Alice';",
      "var age = 30;",
      "var role = 'admin';",
    },
    cursor_start = { 1, 0 },
    goal = {
      buffer_lines = {
        "const name = 'Alice';",
        "const age = 30;",
        "const role = 'admin';",
      },
    },
  },
  {
    category = "Dot Repeat",
    title = "Repeat Delete",
    description = "Delete the comment lines (2, 4, 6) using dd and .",
    teach = { ".", "dd" },
    hint = "dd deletes a line. Use j to skip a line, then . to repeat the deletion",
    par = 6,
    buffer_lines = {
      "host: localhost",
      "# port: 3000",
      "port: 8080",
      "# timeout: 30",
      "timeout: 60",
      "# retries: 3",
      "retries: 5",
    },
    cursor_start = { 2, 0 },
    goal = {
      buffer_lines = {
        "host: localhost",
        "port: 8080",
        "timeout: 60",
        "retries: 5",
      },
    },
  },
  {
    category = "Dot Repeat",
    title = "Repeat Insert",
    description = "Add 'public ' before each method using I and .",
    teach = { ".", "I" },
    hint = "I inserts at first non-blank. Type 'public ', Esc, then j. to repeat",
    par = 13,
    buffer_lines = {
      "class UserService {",
      "  getUser(id) { }",
      "  updateUser(id, data) { }",
      "  deleteUser(id) { }",
      "}",
    },
    cursor_start = { 2, 2 },
    goal = {
      buffer_lines = {
        "class UserService {",
        "  public getUser(id) { }",
        "  public updateUser(id, data) { }",
        "  public deleteUser(id) { }",
        "}",
      },
    },
  },
  {
    category = "Dot Repeat",
    title = "Append Semicolons",
    description = "Append ';' to lines 1-3 using A and dot repeat",
    teach = { ".", "A" },
    hint = "A appends at end of line. Type ; then Esc. Use j. to move down and repeat",
    par = 7,
    buffer_lines = {
      "import React from 'react'",
      "import useState from 'react'",
      "import useEffect from 'react'",
      "",
      "export default App;",
    },
    cursor_start = { 1, 0 },
    goal = {
      buffer_lines = {
        "import React from 'react';",
        "import useState from 'react';",
        "import useEffect from 'react';",
        "",
        "export default App;",
      },
    },
  },
}
