return {
  {
    category = "Search",
    title = "Search Forward",
    description = "Use /TODO to jump to the TODO comment",
    teach = { "/" },
    hint = "Type /TODO and press Enter to search forward for 'TODO'",
    par = 6,
    buffer_lines = {
      "class ShoppingCart {",
      "  constructor() {",
      "    this.items = [];",
      "    this.discount = 0;",
      "  }",
      "",
      "  addItem(item) {",
      "    // TODO: validate item before adding",
      "    this.items.push(item);",
      "  }",
      "",
      "  getTotal() {",
      "    return this.items.reduce((sum, i) => sum + i.price, 0);",
      "  }",
      "}",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 8, 7 } },
  },
  {
    category = "Search",
    title = "Search and Next",
    description = "Find the SECOND 'return' statement (line 8)",
    teach = { "/", "n" },
    hint = "/return then Enter finds the first match. n jumps to the next match",
    par = 9,
    buffer_lines = {
      "function processOrder(order) {",
      "  if (!order) {",
      "    return null;",
      "  }",
      "",
      "  const validated = validate(order);",
      "  if (!validated) {",
      "    return { error: 'Invalid order' };",
      "  }",
      "",
      "  return { success: true, id: order.id };",
      "}",
    },
    cursor_start = { 1, 0 },
    goal = { cursor = { 8, 4 } },
  },
  {
    category = "Search",
    title = "Star Search",
    description = "Use * to find the next occurrence of 'config'",
    teach = { "*" },
    hint = "* searches forward for the exact word under the cursor",
    par = 1,
    buffer_lines = {
      "const config = loadConfig();",
      "",
      "function initApp() {",
      "  const db = connectDB(config.database);",
      "  const cache = initCache(config.redis);",
      "  const server = startServer(config.port);",
      "  return { db, cache, server };",
      "}",
    },
    cursor_start = { 1, 6 },
    goal = { cursor = { 4, 23 } },
  },
  {
    category = "Search",
    title = "Star and Next",
    description = "Jump to the third occurrence of 'data' (line 4)",
    teach = { "*", "n" },
    hint = "* finds next occurrence, then n continues to subsequent matches",
    par = 3,
    buffer_lines = {
      "async function pipeline(data) {",
      "  const cleaned = clean(data);",
      "  const transformed = transform(data);",
      "  const validated = validate(data);",
      "  return save(data);",
      "}",
    },
    cursor_start = { 1, 24 },
    goal = { cursor = { 4, 29 } },
  },
  {
    category = "Search",
    title = "Search Backward",
    description = "From the bottom, search backward for 'error'",
    teach = { "?", "N" },
    hint = "? searches backward (like / but in reverse). Or /pattern then N goes to previous match",
    par = 7,
    buffer_lines = {
      "try {",
      "  const result = await fetchData();",
      "  if (result.error) {",
      "    handleError(result.error);",
      "  }",
      "  return result.data;",
      "} catch (e) {",
      "  logException(e);",
      "  throw e;",
      "}",
    },
    cursor_start = { 10, 0 },
    goal = { cursor = { 4, 16 } },
  },
}
